name: Keep the versions up-to-date

on:
  release:
    types: [published]

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v1
        with:
          publish_latest: true
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
